// Action constants
export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT';
export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS';
export const REASSIGN_TASK = 'REASSIGN_TASK';
export const ADD_NEW_MEMBER = 'ADD_NEW_MEMBER';